#!/bin/sh
JAR_DIR_TOOLS=/home/jakesson/projects/DymolaOptimization/miniModelica/JModelicaAJ
JAR_DIR_APPS=/home/jakesson/projects/DymolaOptimization/miniModelica/Optimica

java -classpath $JAR_DIR_APPS/bin/jmodelica.jar:$JAR_DIR_TOOLS/tools/aspectjrt.jar org.jmodelica.applications.FlattenModel "$@"


#java -Xmx800m -DMODELICA_LIB="$MODELICA_LIB" -DIPOPT="$IPOPT" -classpath $OPTIMI
#CA_DIR/optimica.jar:$OPTIMICA_DIR/tools/beaver.jar  OptimicaCodeGen "$@"

