#!/bin/sh

JAR_DIR=/home/jakesson/projects/DymolaOptimization/miniModelica/JModelicaAJ

java -classpath $JAR_DIR/bin/jmodelica.jar:$JAR_DIR/tools/aspectjrt.jar org.jmodelica.test.benchmarks.GenLocalClasses "$@"


#java -Xmx800m -DMODELICA_LIB="$MODELICA_LIB" -DIPOPT="$IPOPT" -classpath $OPTIMI
#CA_DIR/optimica.jar:$OPTIMICA_DIR/tools/beaver.jar  OptimicaCodeGen "$@"

