// 
//    Copyright (C) 2018 Modelon AB
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the Common Public License as published by
//    IBM, version 1.0 of the License.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY. See the Common Public License for more details.
//
//    You should have received a copy of the Common Public License
//    along with this program.  If not, see
//     <http://www.ibm.com/developerworks/library/os-cpl.html/>.

def ubuntuImage
def centosImage
stage ('Building') {
    parallel Ubuntu: {
        node('docker') {
            checkout scm
            ubuntuImage = docker.build("jmodelica/ubuntu_base", "--no-cache --build-arg DOCKER_LINUX_DIST=ubuntu --build-arg DOCKER_DIST_TAG=18.04 .")
        }
    },
    CentOS: {
        node('docker') {
            checkout scm
            centosImage = docker.build("jmodelica/centos_base", "--no-cache --build-arg DOCKER_LINUX_DIST=centos --build-arg DOCKER_DIST_TAG=7.3.1611 --build-arg DOCKER_USR_PATH=/opt .")
        }
    }
}
node('docker'){
    stage ('Push') {
        docker.withRegistry('https://registry.hub.docker.com', 'jmodelica-dockerhub') {
            ubuntuImage.push("18.04")
            ubuntuImage.push("latest")
            centosImage.push("7.3")
        }
    }
}