function plotSparsityLP(n_x,n_u,n_w,n_p_opt,n_tp, ...
			n_eq_Heq, n_eq_Ceq, ...
			n_e, n_cp, n_eq_F0, n_eq_F, ...
                        dF0_n_cols, dF_dp_n_cols, ...
                        dF_ddx_dx_du_dw_n_cols, indices, ... 
			fig_nbr) 

n_rows = n_eq_F0 + ...
    	 n_eq_F*n_e*n_cp + ...
         n_x*n_e + ...
         n_x*n_e*n_cp + ...
	 n_u + ...
         (2*n_x  + n_u + n_w)*n_tp + ...
         n_eq_Ceq*(n_e*n_cp + 1) + ...
         n_eq_Heq*n_tp

n_cols = n_p_opt + ...
         (2*n_x + n_u + n_w)*(n_e*n_cp + 1) + ...
         n_x*n_e + ...
         (2*n_x + n_u + n_w)*n_tp       

col_F0 = [0.8 0.8 0.8];
col_F = [0.8 0.8 0.8];
col_el_junc = [0.3 0.3 0.3];
col_cp = [0.5 0.5 0.5];


figure(fig_nbr);
clf
p_F0 = patch([0 dF0_n_cols+1 dF0_n_cols+1 0], ...
      [0 0 n_eq_F0+1 n_eq_F0+1],col_F0);  
hold on
set(p_F0,'EdgeAlpha',0);

for i=1:n_e*n_cp,
  p_F = patch([dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*(i-1) ...
       dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*i ...
	dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*i ...
	       dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*(i-1)], ...
       [n_eq_F0 + 1 + n_eq_F*(i-1) ...
        n_eq_F0 + 1 + n_eq_F*(i-1) ...
        n_eq_F0 + 1 + n_eq_F*(i) ...
        n_eq_F0 + 1 + n_eq_F*(i)],col_F);
  set(p_F,'EdgeAlpha',0);
end;




% plot([dF0_n_cols + 1 dF0_n_cols + 1], [0 n_rows+1])

for i=0:n_e,
        
  if (i~=n_e), 
    for j=1:n_cp-1,
      plot([dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*i*n_cp + ...
	  dF_ddx_dx_du_dw_n_cols*j ...
       dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*i*n_cp + ...
	  dF_ddx_dx_du_dw_n_cols*j], ...
       [0 n_rows+1], 'Color', col_cp)
    end
  end
  
  plot([dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*i*n_cp ...
       dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*i*n_cp], ...
       [0 n_rows+1], 'Color', col_el_junc)
  
		       
end;


%for i=0:n_e*n_cp,
%  plot([0,n_cols+1], [n_eq_F0 + 1 + n_eq_F*i ...
%		      n_eq_F0 + 1 + n_eq_F*i], ...
%       'Color',col_cp);
%end


for i=1:n_e,
  plot([dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*n_e*n_cp + ...
	n_x*i ...
       dF0_n_cols + 1 + dF_ddx_dx_du_dw_n_cols*n_e*n_cp + ...
       n_x*i], ...
       [0 n_rows+1], 'Color', col_el_junc)  
end

  plot([0,n_cols+1], [n_eq_F0 + 1 ...
		      n_eq_F0 + 1], ...
      'Color',col_el_junc);


  plot([0,n_cols+1], [n_eq_F0 + 1 + n_eq_F*n_e*n_cp ...
		      n_eq_F0 + 1 + n_eq_F*n_e*n_cp], ...
      'Color',col_el_junc);

  
    plot([0,n_cols+1], [n_eq_F0 + 1 + n_eq_F*n_e*n_cp + ...
			n_x*n_e  ...
		      n_eq_F0 + 1 + n_eq_F*n_e*n_cp + ...
		       n_x*n_e ], ...
      'Color',col_el_junc);

       plot([0,n_cols+1], [n_eq_F0 + 1 + n_eq_F*n_e*n_cp + ...
			n_x*n_e+n_u...
		      n_eq_F0 + 1 + n_eq_F*n_e*n_cp + ...
		       n_x*n_e+n_u], ...
      'Color',col_el_junc);

    
    plot([0,n_cols+1], [n_eq_F0 + 1 + n_eq_F*n_e*n_cp + ...
			n_x*n_e + n_x*n_e*n_cp + n_u...
		      n_eq_F0 + 1 + n_eq_F*n_e*n_cp + ...
		       n_x*n_e + n_x*n_e*n_cp + n_u], ...
      'Color',col_el_junc);


plot(indices(:,3)+0.5,indices(:,2)+0.5,'x');
set(gca,'YDir','reverse');                                     




