/* The following code was generated by JFlex 1.4.3 on 10/6/09 7:14 PM */

/*
    Copyright (C) 2009 Modelon AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package org.jmodelica.modelica.parser;

import beaver.Symbol;
import beaver.Scanner;
import org.jmodelica.modelica.parser.FlatModelicaParser.Terminals;

/*
    Copyright (C) 2009 Modelon AB

    This program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, version 3 of the License.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/



/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/6/09 7:14 PM from the specification file
 * <tt>/home/philip/workspace/JModelicaIDE/src/java-generated/org/jmodelica/modelica/parser/FlatModelica_all.flex</tt>
 */
public final class FlatModelicaScanner extends Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\25\1\24\1\0\1\25\1\23\22\0\1\25\1\0\1\4"+
    "\4\0\1\3\1\43\1\44\1\27\1\21\1\51\1\22\1\16\1\26"+
    "\12\15\1\50\1\47\1\0\1\52\1\0\1\5\1\0\4\1\1\20"+
    "\25\1\1\45\1\2\1\46\1\53\1\1\1\0\1\6\1\7\1\35"+
    "\1\30\1\17\1\10\1\1\1\42\1\34\2\1\1\33\1\37\1\11"+
    "\1\36\1\31\1\41\1\12\1\40\1\13\1\32\1\14\4\1\uff85\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\2\1\2\2\1\3\1\4\1\2"+
    "\1\5\1\6\2\7\1\10\1\11\4\2\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\2\0"+
    "\1\2\2\0\1\23\2\2\1\3\1\0\3\2\1\7"+
    "\1\0\11\2\1\3\1\0\1\2\1\24\1\2\2\0"+
    "\7\2\1\25\1\26\2\0\1\2\1\0\6\2\1\27"+
    "\1\30\1\0\4\2\1\31\2\2\2\0\1\30\3\2"+
    "\1\32\1\2\1\33\1\30\4\2\1\34\2\2\1\35"+
    "\1\36\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\54\0\u0160\0\54\0\54\0\u018c\0\54\0\u01b8\0\54"+
    "\0\u01e4\0\u0210\0\u023c\0\u0268\0\54\0\54\0\54\0\54"+
    "\0\54\0\54\0\54\0\54\0\54\0\u0294\0\u02c0\0\u02c0"+
    "\0\260\0\u02ec\0\54\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8"+
    "\0\u03f4\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04d0\0\u04fc\0\u0528"+
    "\0\u0554\0\u0580\0\u0294\0\u05ac\0\u05d8\0\u0604\0\u0604\0\u0630"+
    "\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738\0\u0764\0\u0790"+
    "\0\u07bc\0\u07e8\0\u0814\0\130\0\130\0\u0840\0\u086c\0\u0898"+
    "\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\130"+
    "\0\u09f8\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\130\0\u0b00"+
    "\0\u0b2c\0\u0b58\0\u0b84\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08\0\130"+
    "\0\u0c34\0\130\0\u0b58\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\130"+
    "\0\u0d10\0\u0d3c\0\130\0\130\0\130";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\2\1\4\1\5\1\2\2\3\1\6"+
    "\2\3\1\7\1\3\1\10\1\11\1\12\1\3\1\13"+
    "\1\14\1\15\2\16\1\17\1\20\1\3\1\21\2\3"+
    "\1\22\1\23\1\24\4\3\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\55\0\1\3\4\0"+
    "\10\3\1\0\2\3\7\0\13\3\11\0\2\36\1\37"+
    "\1\40\50\36\2\41\1\42\1\41\1\43\47\41\1\0"+
    "\1\3\4\0\10\3\1\0\2\3\7\0\4\3\1\44"+
    "\6\3\12\0\1\3\4\0\10\3\1\0\2\3\7\0"+
    "\4\3\1\45\6\3\26\0\1\10\1\46\2\47\34\0"+
    "\1\3\4\0\1\50\2\3\1\51\4\3\1\0\2\3"+
    "\7\0\11\3\1\52\1\3\35\0\1\16\55\0\1\53"+
    "\1\54\25\0\1\3\4\0\1\55\3\3\1\56\3\3"+
    "\1\0\2\3\7\0\2\3\1\57\10\3\12\0\1\3"+
    "\4\0\3\3\1\60\4\3\1\0\2\3\7\0\13\3"+
    "\12\0\1\3\4\0\10\3\1\0\2\3\7\0\6\3"+
    "\1\61\4\3\12\0\1\3\4\0\10\3\1\0\2\3"+
    "\7\0\2\3\1\62\10\3\11\0\3\36\1\63\124\36"+
    "\2\0\13\41\40\0\1\3\4\0\3\3\1\64\4\3"+
    "\1\0\2\3\7\0\13\3\12\0\1\3\4\0\10\3"+
    "\1\0\2\3\7\0\7\3\1\65\3\3\26\0\1\46"+
    "\1\0\2\47\50\0\1\66\3\0\2\67\32\0\1\3"+
    "\4\0\10\3\1\0\2\3\7\0\5\3\1\70\5\3"+
    "\12\0\1\3\4\0\10\3\1\0\2\3\7\0\1\71"+
    "\12\3\12\0\1\3\4\0\10\3\1\0\2\3\7\0"+
    "\2\3\1\72\10\3\11\0\23\53\1\15\1\16\27\53"+
    "\27\73\1\74\24\73\1\0\1\3\4\0\4\3\1\75"+
    "\3\3\1\0\2\3\7\0\13\3\12\0\1\3\4\0"+
    "\10\3\1\0\2\3\7\0\6\3\1\76\4\3\12\0"+
    "\1\3\4\0\1\3\1\77\6\3\1\0\2\3\7\0"+
    "\13\3\12\0\1\3\4\0\10\3\1\0\2\3\7\0"+
    "\1\3\1\100\11\3\12\0\1\3\4\0\3\3\1\101"+
    "\4\3\1\0\2\3\7\0\13\3\12\0\1\3\4\0"+
    "\5\3\1\102\2\3\1\0\2\3\7\0\13\3\12\0"+
    "\1\3\4\0\1\103\7\3\1\0\2\3\7\0\13\3"+
    "\12\0\1\3\4\0\10\3\1\0\1\104\1\3\7\0"+
    "\13\3\26\0\1\66\37\0\1\3\4\0\10\3\1\0"+
    "\2\3\7\0\12\3\1\105\12\0\1\3\4\0\10\3"+
    "\1\0\2\3\2\0\1\106\2\107\2\0\13\3\12\0"+
    "\1\3\4\0\1\110\7\3\1\0\2\3\7\0\13\3"+
    "\11\0\27\73\1\111\24\73\26\0\1\16\1\74\25\0"+
    "\1\3\4\0\1\112\7\3\1\0\2\3\7\0\13\3"+
    "\12\0\1\3\4\0\5\3\1\113\2\3\1\0\2\3"+
    "\7\0\13\3\12\0\1\3\4\0\10\3\1\0\2\3"+
    "\7\0\3\3\1\114\7\3\12\0\1\3\4\0\10\3"+
    "\1\0\2\3\7\0\2\3\1\115\10\3\12\0\1\3"+
    "\4\0\10\3\1\0\2\3\7\0\10\3\1\116\2\3"+
    "\12\0\1\3\4\0\10\3\1\0\2\3\7\0\1\3"+
    "\1\117\11\3\12\0\1\3\4\0\10\3\1\0\2\3"+
    "\7\0\3\3\1\120\7\3\12\0\1\121\1\0\1\122"+
    "\2\0\7\121\2\0\2\121\3\0\1\107\3\0\13\121"+
    "\12\0\1\121\1\0\1\122\2\0\7\121\2\0\2\121"+
    "\7\0\13\121\12\0\1\3\4\0\5\3\1\123\2\3"+
    "\1\0\2\3\7\0\13\3\11\0\26\73\1\16\1\111"+
    "\24\73\1\0\1\3\4\0\10\3\1\0\2\3\7\0"+
    "\7\3\1\124\3\3\12\0\1\3\4\0\10\3\1\0"+
    "\1\125\1\3\7\0\13\3\12\0\1\3\4\0\10\3"+
    "\1\0\2\3\7\0\4\3\1\126\6\3\12\0\1\3"+
    "\4\0\5\3\1\127\2\3\1\0\2\3\7\0\13\3"+
    "\12\0\1\3\4\0\5\3\1\130\2\3\1\0\2\3"+
    "\7\0\13\3\12\0\1\3\4\0\10\3\1\0\2\3"+
    "\7\0\2\3\1\131\10\3\12\0\1\121\4\0\10\121"+
    "\1\0\2\121\7\0\13\121\11\0\2\132\1\133\1\134"+
    "\50\132\1\0\1\3\4\0\10\3\1\0\2\3\7\0"+
    "\4\3\1\135\6\3\12\0\1\3\4\0\10\3\1\0"+
    "\1\136\1\3\7\0\13\3\12\0\1\3\4\0\10\3"+
    "\1\0\2\3\7\0\5\3\1\137\5\3\12\0\1\3"+
    "\4\0\10\3\1\0\2\3\7\0\5\3\1\140\5\3"+
    "\12\0\1\3\4\0\1\141\7\3\1\0\2\3\7\0"+
    "\13\3\12\0\1\3\4\0\5\3\1\142\2\3\1\0"+
    "\2\3\7\0\13\3\11\0\3\132\1\143\124\132\1\0"+
    "\1\3\4\0\10\3\1\0\2\3\7\0\6\3\1\144"+
    "\4\3\12\0\1\3\4\0\5\3\1\145\2\3\1\0"+
    "\2\3\7\0\13\3\12\0\1\3\4\0\5\3\1\146"+
    "\2\3\1\0\2\3\7\0\13\3\12\0\1\3\4\0"+
    "\3\3\1\147\4\3\1\0\2\3\7\0\13\3\12\0"+
    "\1\3\4\0\3\3\1\150\4\3\1\0\2\3\7\0"+
    "\13\3\12\0\1\3\4\0\10\3\1\0\1\151\1\3"+
    "\7\0\13\3\12\0\1\3\4\0\10\3\1\0\1\152"+
    "\1\3\7\0\13\3\12\0\1\3\4\0\5\3\1\153"+
    "\2\3\1\0\2\3\7\0\13\3\12\0\1\3\4\0"+
    "\4\3\1\154\3\3\1\0\2\3\7\0\13\3\12\0"+
    "\1\3\4\0\10\3\1\0\2\3\7\0\1\155\12\3"+
    "\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[3432];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\6\1\1\11\1\1\2\11\1\1\1\11"+
    "\1\1\1\11\4\1\11\11\2\0\1\1\2\0\1\11"+
    "\3\1\1\0\4\1\1\0\12\1\1\0\3\1\2\0"+
    "\11\1\2\0\1\1\1\0\10\1\1\0\7\1\2\0"+
    "\22\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[109];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer(128);

  private Symbol newSymbol(short id) {
    return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), yytext());
  }

  private Symbol newSymbol(short id, Object value) {
    return new Symbol(id, yyline + 1, yycolumn + 1, yylength(), value);
  }



  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public FlatModelicaScanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public FlatModelicaScanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 120) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Symbol nextToken() throws java.io.IOException, Scanner.Exception {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 7: 
          { /* discard token */
          }
        case 32: break;
        case 28: 
          { return newSymbol(Terminals.EQUATION);
          }
        case 33: break;
        case 21: 
          { return newSymbol(Terminals.TIME);
          }
        case 34: break;
        case 1: 
          { throw new Scanner.Exception(yyline,yycolumn,"Illegal character \""+yytext()+ "\" at line "+yyline+", column "+yycolumn);
          }
        case 35: break;
        case 2: 
          { return newSymbol(Terminals.ID, yytext());
          }
        case 36: break;
        case 6: 
          { return newSymbol(Terminals.MINUS);
          }
        case 37: break;
        case 10: 
          { return newSymbol(Terminals.LPAREN);
          }
        case 38: break;
        case 27: 
          { return newSymbol(Terminals.OUTPUT);
          }
        case 39: break;
        case 12: 
          { return newSymbol(Terminals.LBRACK);
          }
        case 40: break;
        case 23: 
          { return newSymbol(Terminals.FINAL);
          }
        case 41: break;
        case 25: 
          { return newSymbol(Terminals.INPUT);
          }
        case 42: break;
        case 3: 
          { return newSymbol(Terminals.UNSIGNED_NUMBER, yytext());
          }
        case 43: break;
        case 29: 
          { return newSymbol(Terminals.CONSTANT);
          }
        case 44: break;
        case 5: 
          { return newSymbol(Terminals.PLUS);
          }
        case 45: break;
        case 22: 
          { return newSymbol(Terminals.EACH);
          }
        case 46: break;
        case 20: 
          { return newSymbol(Terminals.END);
          }
        case 47: break;
        case 17: 
          { return newSymbol(Terminals.ASSIGN);
          }
        case 48: break;
        case 24: 
          { String s = yytext();
  			  return newSymbol(Terminals.END_ID, s);
          }
        case 49: break;
        case 11: 
          { return newSymbol(Terminals.RPAREN);
          }
        case 50: break;
        case 15: 
          { return newSymbol(Terminals.COLON);
          }
        case 51: break;
        case 9: 
          { return newSymbol(Terminals.MULT);
          }
        case 52: break;
        case 26: 
          { return newSymbol(Terminals.PUBLIC);
          }
        case 53: break;
        case 13: 
          { return newSymbol(Terminals.RBRACK);
          }
        case 54: break;
        case 4: 
          { return newSymbol(Terminals.DOT);
          }
        case 55: break;
        case 16: 
          { return newSymbol(Terminals.COMMA);
          }
        case 56: break;
        case 18: 
          { return newSymbol(Terminals.POW);
          }
        case 57: break;
        case 30: 
          { return newSymbol(Terminals.PARAMETER);
          }
        case 58: break;
        case 31: 
          { return newSymbol(Terminals.PROTECTED);
          }
        case 59: break;
        case 19: 
          { String s = yytext();
               s = s.substring(1,s.length()-1);
                return newSymbol(Terminals.STRING,s);
          }
        case 60: break;
        case 14: 
          { return newSymbol(Terminals.SEMICOLON);
          }
        case 61: break;
        case 8: 
          { return newSymbol(Terminals.DIV);
          }
        case 62: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
              {
                return newSymbol(Terminals.EOF);
              }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
