#!/bin/bash
# 
#    Copyright (C) 2018 Modelon AB
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the Common Public License as published by
#    IBM, version 1.0 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY. See the Common Public License for more details.
#
#    You should have received a copy of the Common Public License
#    along with this program.  If not, see
#     <http://www.ibm.com/developerworks/library/os-cpl.html/>.



echo "========================================"
echo "using FMIL_INSTALL_DIR=$FMIL_INSTALL_DIR"
echo "========================================"
# variables are sourced already in build system
# The X is just to allow empty strings
if [[ X"$1" = X"PYFMI_BASE" ]]; then
cat <<EOF> $(dirname     "$0")/Dockerfile
# Automatically generated by generate_dockerfile.sh
ARG LINUX_DIST=${PLATFORM}
ARG DIST_VERSION=${DIST_VERSION}
ARG PYTHON_VERSION=${PYTHON_VERSION}
ARG BUILD_TARGET=${BUILD_TARGET}

# starting linux environment
FROM \$LINUX_DIST:\$DIST_VERSION
LABEL maintainer="Modelon AB"
RUN mkdir -p fmil && mkdir -p build_scripts
COPY ${PLATFORM}_${DIST_VERSION}/fmil_install /fmil
COPY build_environment/platforms/${PLATFORM}/*.sh build_scripts/
RUN if [ ${PLATFORM} = "ubuntu" ]; then apt-get update && apt-get install -y make gcc; else yum install -y make gcc; fi

RUN build_scripts/install_python.sh

# cleanup
RUN rm -rf build_scripts
EOF
else
cat <<EOF> $(dirname     "$0")/Dockerfile
# Automatically generated by generate_dockerfile.sh
ARG LINUX_DIST=${PLATFORM}
ARG DIST_VERSION=${DIST_VERSION}
ARG PYTHON_VERSION=${PYTHON_VERSION}
ARG BUILD_TARGET=${BUILD_TARGET}

# starting linux environment
FROM \$LINUX_DIST:\$DIST_VERSION
LABEL maintainer="Modelon AB"
#TODO add script to get rid of "if..."
RUN if [ ${PLATFORM} = "ubuntu" ]; then apt-get update && apt-get install -y make; else yum install -y make; fi

# cleanup
RUN echo "TODO: Add cleanup script"
EOF
fi
