// 
//    Copyright (C) 2018 Modelon AB
//
//    This program is free software: you can redistribute it and/or modify
//    it under the terms of the Common Public License as published by
//    IBM, version 1.0 of the License.
//
//    This program is distributed in the hope that it will be useful,
//    but WITHOUT ANY WARRANTY. See the Common Public License for more details.
//
//    You should have received a copy of the Common Public License
//    along with this program.  If not, see
//     <http://www.ibm.com/developerworks/library/os-cpl.html/>.

def ubuntuImage18_04
def centosImage7_4
def buildBaseImage(targetName, linuxDist, distTag) {
    return docker.build("jmodelica/$targetName", "--no-cache --pull --build-arg DOCKER_LINUX_DIST=$linuxDist --build-arg DOCKER_DIST_TAG=$distTag .")
}
stage ('Building') {
    parallel Ubuntu: {
        node('docker') {
            checkout scm
            ubuntuImage18_04 = buildBaseImage("ubuntu_base", "ubuntu", "18.04")
        }
    },
    CentOS7_4: {
        node('docker') {
            checkout scm
            centosImage7_4 = buildBaseImage("centos_base", "centos", "7.4.1708")
            centosImage7_4.inside {
                sh 'echo Built version: && cat /etc/centos-release'
                sh 'cat /etc/passwd'
                sh 'whoami'
                sh 'sed -i "/^backend/c\\backend:Agg" $(python -c "import matplotlib;print(matplotlib.matplotlib_fname())")'
            }
        }
    }
}
node('docker'){
    stage ('Push') {
        docker.withRegistry('https://registry.hub.docker.com', 'jmodelica-dockerhub') {
            ubuntuImage18_04.push("ubuntu-dev")
            centosImage7_4.push("centos-dev")
        }
    }
}