#!/bin/sh


#    Copyright (C) 2009 Modelon AB
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, version 3 of the License.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


JAR_DIR_TOOLS=/home/jakesson/projects/DymolaOptimization/miniModelica/JModelicaAJ
JAR_DIR_APPS=/home/jakesson/projects/DymolaOptimization/miniModelica/Optimica

java -classpath $JAR_DIR_APPS/bin/jmodelica.jar:$JAR_DIR_TOOLS/tools/aspectjrt.jar org.jmodelica.applications.FlattenModel "$@"


#java -Xmx800m -DMODELICA_LIB="$MODELICA_LIB" -DIPOPT="$IPOPT" -classpath $OPTIMI
#CA_DIR/optimica.jar:$OPTIMICA_DIR/tools/beaver.jar  OptimicaCodeGen "$@"

