ARG DOCKER_LINUX_DIST=ubuntu
ARG DOCKER_DIST_TAG=latest

FROM $DOCKER_LINUX_DIST:$DOCKER_DIST_TAG
MAINTAINER Modelon

ARG DOCKER_LINUX_DIST
ARG DOCKER_DIST_TAG
ARG DOCKER_USR_PATH=/opt
ARG DOCKER_JM_TESTS_WS=/tmp

ENV USR_PATH=${DOCKER_USR_PATH}
ENV JM_TESTS_WS=${DOCKER_JM_TESTS_WS}

# TODO Argument checking user need to create images only of tested distributions ...

#if [ DOCKER_LINUX_DIST==ubuntu] ; then
#	RUN apt list --installed;
#else
#	RUN yum list installed;  
#fi

COPY Docker/*.sh ${USR_PATH}/Docker/build/
COPY Docker/*.py ${USR_PATH}/Docker/build/
RUN ls -la
COPY / ${USR_PATH}/JModelica.org/
RUN chmod +x ${USR_PATH}/Docker/build/*.sh
RUN ls -la ${USR_PATH}/Docker/build
RUN ${USR_PATH}/Docker/build/run_scripts.sh
#RUN mkdir -p $JM_TESTS_WS/test_results && chmod 777 $USR_PATH && chmod 777 $JM_TESTS_WS/test_results
#RUN $USR_PATH/Docker/build/cleanup.sh