ARG DOCKER_LINUX_DIST=ubuntu
ARG DOCKER_DIST_TAG=latest
# TODO Argument checking user need to create images only of tested distributions ...

FROM $DOCKER_LINUX_DIST:$DOCKER_DIST_TAG
MAINTAINER Modelon

COPY Docker/*.sh Docker/build/
COPY Docker/*.py Docker/build/
COPY . /JModelica.org/
RUN chmod +x Docker/build/*.sh
#RUN Docker/build/run_scripts.sh