ARG DOCKER_LINUX_DIST=jmodelica/ubuntu_base
ARG DOCKER_DIST_TAG=latest

# TODO Argument checking user need to create images only of tested distributions ...

FROM $DOCKER_LINUX_DIST:$DOCKER_DIST_TAG
MAINTAINER Modelon

# The following variables need to get redeclared again .. no idea why 
ARG DOCKER_LINUX_DIST
ARG DOCKER_DIST_TAG

ARG DOCKER_JM_TESTS_WS=/home/jenkins/internal/workspace/OCTTeam/JM_Ubuntu-Build
ARG DOCKER_USR_PATH=/home/jenkins

ENV USR_PATH=${DOCKER_USR_PATH}
ENV JM_TESTS_WS=${DOCKER_JM_TESTS_WS}

RUN apt list --installed
#RUN if [ "$DOCKER_LINUX_DIST"=="ubuntu" ] ; then apt list --installed ; else yum list installed ; fi


COPY Docker/*.sh ${USR_PATH}/Docker/build/
COPY Docker/*.py ${USR_PATH}/Docker/build/

RUN ls -la && pwd

COPY / ${USR_PATH}/JModelica.org/

RUN chmod +x ${USR_PATH}/Docker/build/*.sh
RUN ls -la ${USR_PATH}/Docker/build
RUN ${USR_PATH}/Docker/build/run_full_scripts.sh
RUN chmod -R 777 ${USR_PATH}
RUN cd ${USR_PATH}/jm_install && mkdir -p $JM_TESTS_WS/test_results && ls -la && ./jm_tests -i -x "$JM_TESTS_WS/test_results" -f "test_examples_jmi.py"

#RUN ${USR_PATH}/Docker/build/cleanup.sh